### ISSUE TITLE
Redazione verbali

### ISSUE THREAD

**Issue by abenetazzo** [7Last/docs#2]
Redarre i verbali esterni e interni in LateX secondo il template (aspettare che Matteo lo aggiorni?).
Occhio che per i verbali esterni serve la conferma (via mail o firma su verbale) da parte dell'azienda coinvolta!

- [x] Prima call 05/03 (interno)
- [x] Incontro SyncLab 08/03 (esterno)
- [x] Incontro Zucchetti 08/03 (esterno)
- [x] Incontro Imola Informatica 15/03 (esterno)
- [x] Seconda call 15/03 (interno)
- [ ] Conferma verbali esterni

**Comment by Valerio-Occhinegro** [comment]
Caricati tutti i verbali nel branch feature/verbali
Necessaria revisione da parte dei membri del gruppo per successivo inoltro dei verbali esterni alle aziende.
